const LISTA_PRIORIDADES = ['baixa', 'média', 'alta'];

const PRIORIDADES = {
  BAIXA: LISTA_PRIORIDADES[0],
  MEDIA: LISTA_PRIORIDADES[1],
  ALTA: LISTA_PRIORIDADES[2],
};

module.exports = {
  LISTA_PRIORIDADES,
  PRIORIDADES,
};
